// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Abar61v3PSTTOszMkWB9KiiHtLUCQR8',
    appId: '1:190786814427:web:360b5017b62096235ea7fe',
    messagingSenderId: '190786814427',
    projectId: 'pr-app-d4bca',
    authDomain: 'pr-app-d4bca.firebaseapp.com',
    storageBucket: 'pr-app-d4bca.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAuau4Cwz437j14oyDntAOgOujQRzr9hqA',
    appId: '1:190786814427:android:fe11e46a456a2fcf5ea7fe',
    messagingSenderId: '190786814427',
    projectId: 'pr-app-d4bca',
    storageBucket: 'pr-app-d4bca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCZcResmrKECXD8VJlzBQw24dys4wYANw',
    appId: '1:190786814427:ios:f20608fd2c1784715ea7fe',
    messagingSenderId: '190786814427',
    projectId: 'pr-app-d4bca',
    storageBucket: 'pr-app-d4bca.firebasestorage.app',
    iosBundleId: 'com.example.drDashbord',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDCZcResmrKECXD8VJlzBQw24dys4wYANw',
    appId: '1:190786814427:ios:f20608fd2c1784715ea7fe',
    messagingSenderId: '190786814427',
    projectId: 'pr-app-d4bca',
    storageBucket: 'pr-app-d4bca.firebasestorage.app',
    iosBundleId: 'com.example.drDashbord',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Abar61v3PSTTOszMkWB9KiiHtLUCQR8',
    appId: '1:190786814427:web:e466bce0bd94cb2d5ea7fe',
    messagingSenderId: '190786814427',
    projectId: 'pr-app-d4bca',
    authDomain: 'pr-app-d4bca.firebaseapp.com',
    storageBucket: 'pr-app-d4bca.firebasestorage.app',
  );
}
